/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HospitalPaymentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "RECORDER_ROLE"
      | "appointmentPayments"
      | "getPatientPayments"
      | "getPayment"
      | "getPaymentByAppointment"
      | "getPaymentHistory"
      | "getRoleAdmin"
      | "getStatistics"
      | "grantRecorderRole"
      | "grantRole"
      | "hasRole"
      | "patientPayments"
      | "paymentHistory"
      | "payments"
      | "recordPayment"
      | "refundPayment"
      | "renounceRole"
      | "revokeRecorderRole"
      | "revokeRole"
      | "supportsInterface"
      | "totalAmountRecorded"
      | "totalPaymentsRecorded"
      | "updatePaymentStatus"
      | "verifyPayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentRecorded"
      | "PaymentRefunded"
      | "PaymentStatusUpdated"
      | "PaymentVerified"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RECORDER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "appointmentPayments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientPayments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentByAppointment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRecorderRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "patientPayments",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "payments", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "recordPayment",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundPayment",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRecorderRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAmountRecorded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPaymentsRecorded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePaymentStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPayment",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RECORDER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appointmentPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentByAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantRecorderRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeRecorderRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAmountRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPaymentsRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePaymentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPayment",
    data: BytesLike
  ): Result;
}

export namespace PaymentRecordedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    appointmentId: BytesLike,
    dataHash: BytesLike,
    amount: BigNumberish,
    timestamp: BigNumberish,
    recorder: AddressLike
  ];
  export type OutputTuple = [
    paymentId: string,
    appointmentId: string,
    dataHash: string,
    amount: bigint,
    timestamp: bigint,
    recorder: string
  ];
  export interface OutputObject {
    paymentId: string;
    appointmentId: string;
    dataHash: string;
    amount: bigint;
    timestamp: bigint;
    recorder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRefundedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    refundAmount: BigNumberish,
    timestamp: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    paymentId: string,
    refundAmount: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    paymentId: string;
    refundAmount: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentStatusUpdatedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    oldStatus: bigint,
    newStatus: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    oldStatus: bigint;
    newStatus: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentVerifiedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    dataHash: BytesLike,
    timestamp: BigNumberish,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    paymentId: string,
    dataHash: string,
    timestamp: bigint,
    verifier: string
  ];
  export interface OutputObject {
    paymentId: string;
    dataHash: string;
    timestamp: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HospitalPaymentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HospitalPaymentRegistry;
  waitForDeployment(): Promise<this>;

  interface: HospitalPaymentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  RECORDER_ROLE: TypedContractMethod<[], [string], "view">;

  appointmentPayments: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getPatientPayments: TypedContractMethod<
    [_patient: AddressLike],
    [string[]],
    "view"
  >;

  getPayment: TypedContractMethod<
    [_paymentId: BytesLike],
    [
      [string, bigint, bigint, string, bigint] & {
        dataHash: string;
        amount: bigint;
        timestamp: bigint;
        recorder: string;
        status: bigint;
      }
    ],
    "view"
  >;

  getPaymentByAppointment: TypedContractMethod<
    [_appointmentId: BytesLike],
    [string],
    "view"
  >;

  getPaymentHistory: TypedContractMethod<
    [_paymentId: BytesLike],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStatistics: TypedContractMethod<
    [],
    [[bigint, bigint] & { totalPayments: bigint; totalAmount: bigint }],
    "view"
  >;

  grantRecorderRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  patientPayments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  paymentHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  payments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, bigint, boolean] & {
        dataHash: string;
        amount: bigint;
        timestamp: bigint;
        recorder: string;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  recordPayment: TypedContractMethod<
    [
      _paymentId: BytesLike,
      _appointmentId: BytesLike,
      _dataHash: BytesLike,
      _amount: BigNumberish,
      _patient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  refundPayment: TypedContractMethod<
    [_paymentId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRecorderRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalAmountRecorded: TypedContractMethod<[], [bigint], "view">;

  totalPaymentsRecorded: TypedContractMethod<[], [bigint], "view">;

  updatePaymentStatus: TypedContractMethod<
    [_paymentId: BytesLike, _newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyPayment: TypedContractMethod<
    [_paymentId: BytesLike, _dataHash: BytesLike],
    [
      [boolean, bigint, bigint, bigint] & {
        isValid: boolean;
        status: bigint;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RECORDER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "appointmentPayments"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPatientPayments"
  ): TypedContractMethod<[_patient: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [_paymentId: BytesLike],
    [
      [string, bigint, bigint, string, bigint] & {
        dataHash: string;
        amount: bigint;
        timestamp: bigint;
        recorder: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentByAppointment"
  ): TypedContractMethod<[_appointmentId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPaymentHistory"
  ): TypedContractMethod<[_paymentId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStatistics"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { totalPayments: bigint; totalAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRecorderRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "patientPayments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "paymentHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, bigint, boolean] & {
        dataHash: string;
        amount: bigint;
        timestamp: bigint;
        recorder: string;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordPayment"
  ): TypedContractMethod<
    [
      _paymentId: BytesLike,
      _appointmentId: BytesLike,
      _dataHash: BytesLike,
      _amount: BigNumberish,
      _patient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundPayment"
  ): TypedContractMethod<
    [_paymentId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRecorderRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalAmountRecorded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPaymentsRecorded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePaymentStatus"
  ): TypedContractMethod<
    [_paymentId: BytesLike, _newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyPayment"
  ): TypedContractMethod<
    [_paymentId: BytesLike, _dataHash: BytesLike],
    [
      [boolean, bigint, bigint, bigint] & {
        isValid: boolean;
        status: bigint;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PaymentRecorded"
  ): TypedContractEvent<
    PaymentRecordedEvent.InputTuple,
    PaymentRecordedEvent.OutputTuple,
    PaymentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRefunded"
  ): TypedContractEvent<
    PaymentRefundedEvent.InputTuple,
    PaymentRefundedEvent.OutputTuple,
    PaymentRefundedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentStatusUpdated"
  ): TypedContractEvent<
    PaymentStatusUpdatedEvent.InputTuple,
    PaymentStatusUpdatedEvent.OutputTuple,
    PaymentStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentVerified"
  ): TypedContractEvent<
    PaymentVerifiedEvent.InputTuple,
    PaymentVerifiedEvent.OutputTuple,
    PaymentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "PaymentRecorded(bytes32,bytes32,bytes32,uint256,uint256,address)": TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;
    PaymentRecorded: TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;

    "PaymentRefunded(bytes32,uint256,uint256,string)": TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;
    PaymentRefunded: TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;

    "PaymentStatusUpdated(bytes32,uint8,uint8,uint256)": TypedContractEvent<
      PaymentStatusUpdatedEvent.InputTuple,
      PaymentStatusUpdatedEvent.OutputTuple,
      PaymentStatusUpdatedEvent.OutputObject
    >;
    PaymentStatusUpdated: TypedContractEvent<
      PaymentStatusUpdatedEvent.InputTuple,
      PaymentStatusUpdatedEvent.OutputTuple,
      PaymentStatusUpdatedEvent.OutputObject
    >;

    "PaymentVerified(bytes32,bytes32,uint256,address)": TypedContractEvent<
      PaymentVerifiedEvent.InputTuple,
      PaymentVerifiedEvent.OutputTuple,
      PaymentVerifiedEvent.OutputObject
    >;
    PaymentVerified: TypedContractEvent<
      PaymentVerifiedEvent.InputTuple,
      PaymentVerifiedEvent.OutputTuple,
      PaymentVerifiedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
