/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HospitalMedicalRecordRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "RECORDER_ROLE"
      | "appointmentRecords"
      | "createRecord"
      | "getAppointmentRecords"
      | "getRecord"
      | "getRoleAdmin"
      | "getStatistics"
      | "getUploaderRecords"
      | "grantRecorderRole"
      | "grantRole"
      | "hasRole"
      | "records"
      | "renounceRole"
      | "revokeRecord"
      | "revokeRecorderRole"
      | "revokeRole"
      | "supportsInterface"
      | "totalRecords"
      | "uploaderRecords"
      | "verifyRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RecordCreated"
      | "RecordRevoked"
      | "RecordVerified"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RECORDER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "appointmentRecords",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRecord",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppointmentRecords",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUploaderRecords",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRecorderRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "records", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRecord",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRecorderRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uploaderRecords",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRecord",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RECORDER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appointmentRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppointmentRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUploaderRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantRecorderRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeRecorderRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploaderRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRecord",
    data: BytesLike
  ): Result;
}

export namespace RecordCreatedEvent {
  export type InputTuple = [
    recordId: BytesLike,
    appointmentId: BytesLike,
    dataHash: BytesLike,
    recordType: BigNumberish,
    timestamp: BigNumberish,
    uploader: AddressLike
  ];
  export type OutputTuple = [
    recordId: string,
    appointmentId: string,
    dataHash: string,
    recordType: bigint,
    timestamp: bigint,
    uploader: string
  ];
  export interface OutputObject {
    recordId: string;
    appointmentId: string;
    dataHash: string;
    recordType: bigint;
    timestamp: bigint;
    uploader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordRevokedEvent {
  export type InputTuple = [
    recordId: BytesLike,
    timestamp: BigNumberish,
    revoker: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    recordId: string,
    timestamp: bigint,
    revoker: string,
    reason: string
  ];
  export interface OutputObject {
    recordId: string;
    timestamp: bigint;
    revoker: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordVerifiedEvent {
  export type InputTuple = [
    recordId: BytesLike,
    dataHash: BytesLike,
    isValid: boolean,
    timestamp: BigNumberish,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    recordId: string,
    dataHash: string,
    isValid: boolean,
    timestamp: bigint,
    verifier: string
  ];
  export interface OutputObject {
    recordId: string;
    dataHash: string;
    isValid: boolean;
    timestamp: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HospitalMedicalRecordRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HospitalMedicalRecordRegistry;
  waitForDeployment(): Promise<this>;

  interface: HospitalMedicalRecordRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  RECORDER_ROLE: TypedContractMethod<[], [string], "view">;

  appointmentRecords: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  createRecord: TypedContractMethod<
    [
      _recordId: BytesLike,
      _appointmentId: BytesLike,
      _dataHash: BytesLike,
      _recordType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAppointmentRecords: TypedContractMethod<
    [_appointmentId: BytesLike],
    [string[]],
    "view"
  >;

  getRecord: TypedContractMethod<
    [_recordId: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        dataHash: string;
        appointmentId: string;
        uploader: string;
        recordType: bigint;
        timestamp: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStatistics: TypedContractMethod<[], [bigint], "view">;

  getUploaderRecords: TypedContractMethod<
    [_uploader: AddressLike],
    [string[]],
    "view"
  >;

  grantRecorderRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  records: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        dataHash: string;
        appointmentId: string;
        uploader: string;
        recordType: bigint;
        timestamp: bigint;
        exists: boolean;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRecord: TypedContractMethod<
    [_recordId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;

  revokeRecorderRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalRecords: TypedContractMethod<[], [bigint], "view">;

  uploaderRecords: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  verifyRecord: TypedContractMethod<
    [_recordId: BytesLike, _dataHash: BytesLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isValid: boolean;
        isRevoked: boolean;
        recordType: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RECORDER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "appointmentRecords"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createRecord"
  ): TypedContractMethod<
    [
      _recordId: BytesLike,
      _appointmentId: BytesLike,
      _dataHash: BytesLike,
      _recordType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAppointmentRecords"
  ): TypedContractMethod<[_appointmentId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [_recordId: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        dataHash: string;
        appointmentId: string;
        uploader: string;
        recordType: bigint;
        timestamp: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStatistics"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUploaderRecords"
  ): TypedContractMethod<[_uploader: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRecorderRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        dataHash: string;
        appointmentId: string;
        uploader: string;
        recordType: bigint;
        timestamp: bigint;
        exists: boolean;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRecord"
  ): TypedContractMethod<
    [_recordId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRecorderRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "uploaderRecords"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyRecord"
  ): TypedContractMethod<
    [_recordId: BytesLike, _dataHash: BytesLike],
    [
      [boolean, boolean, bigint, bigint] & {
        isValid: boolean;
        isRevoked: boolean;
        recordType: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RecordCreated"
  ): TypedContractEvent<
    RecordCreatedEvent.InputTuple,
    RecordCreatedEvent.OutputTuple,
    RecordCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RecordRevoked"
  ): TypedContractEvent<
    RecordRevokedEvent.InputTuple,
    RecordRevokedEvent.OutputTuple,
    RecordRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RecordVerified"
  ): TypedContractEvent<
    RecordVerifiedEvent.InputTuple,
    RecordVerifiedEvent.OutputTuple,
    RecordVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "RecordCreated(bytes32,bytes32,bytes32,uint8,uint256,address)": TypedContractEvent<
      RecordCreatedEvent.InputTuple,
      RecordCreatedEvent.OutputTuple,
      RecordCreatedEvent.OutputObject
    >;
    RecordCreated: TypedContractEvent<
      RecordCreatedEvent.InputTuple,
      RecordCreatedEvent.OutputTuple,
      RecordCreatedEvent.OutputObject
    >;

    "RecordRevoked(bytes32,uint256,address,string)": TypedContractEvent<
      RecordRevokedEvent.InputTuple,
      RecordRevokedEvent.OutputTuple,
      RecordRevokedEvent.OutputObject
    >;
    RecordRevoked: TypedContractEvent<
      RecordRevokedEvent.InputTuple,
      RecordRevokedEvent.OutputTuple,
      RecordRevokedEvent.OutputObject
    >;

    "RecordVerified(bytes32,bytes32,bool,uint256,address)": TypedContractEvent<
      RecordVerifiedEvent.InputTuple,
      RecordVerifiedEvent.OutputTuple,
      RecordVerifiedEvent.OutputObject
    >;
    RecordVerified: TypedContractEvent<
      RecordVerifiedEvent.InputTuple,
      RecordVerifiedEvent.OutputTuple,
      RecordVerifiedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
