/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HospitalMedicalRecordRegistry__factory } from "./HospitalMedicalRecordRegistry__factory";
export { HospitalPaymentRegistry__factory } from "./HospitalPaymentRegistry__factory";
